version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    restart: unless-stopped

networks:
  default:
    driver: bridge
